apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../deployment.yaml
  - ../../service.yaml
  - ../../ingress.yaml
namespace: python-app-green
images:
- name: elisska/hello-gitops
  newTag: green
patchesStrategicMerge:
  - patch-green.yaml
