apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
        - name: my-app
          image: pavlyukm/hello-gitops:green  # Unique image tag for green
