apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
        - name: my-app
          image: elisska/hello-gitops:blue  # Unique image tag for blue
